version: "3.8"

services:
  api:
    container_name: LibreChat
    ports:
      - "${PORT}:${PORT}"
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: "${UID}:${GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=${MONGO_URI}         # Use your remote MongoDB URL via .env
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./librechat.yaml:/app/config/librechat.yaml  # 👈 this mounts your config
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
